// Generated by gencpp from file Piotr_Dabrowski/AddTwoInts.msg
// DO NOT EDIT!


#ifndef PIOTR_DABROWSKI_MESSAGE_ADDTWOINTS_H
#define PIOTR_DABROWSKI_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <Piotr_Dabrowski/AddTwoIntsRequest.h>
#include <Piotr_Dabrowski/AddTwoIntsResponse.h>


namespace Piotr_Dabrowski
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace Piotr_Dabrowski


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::Piotr_Dabrowski::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::Piotr_Dabrowski::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::Piotr_Dabrowski::AddTwoInts > {
  static const char* value()
  {
    return "Piotr_Dabrowski/AddTwoInts";
  }

  static const char* value(const ::Piotr_Dabrowski::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::Piotr_Dabrowski::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::Piotr_Dabrowski::AddTwoInts > 
template<>
struct MD5Sum< ::Piotr_Dabrowski::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::Piotr_Dabrowski::AddTwoInts >::value();
  }
  static const char* value(const ::Piotr_Dabrowski::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::Piotr_Dabrowski::AddTwoIntsRequest> should match 
// service_traits::DataType< ::Piotr_Dabrowski::AddTwoInts > 
template<>
struct DataType< ::Piotr_Dabrowski::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::Piotr_Dabrowski::AddTwoInts >::value();
  }
  static const char* value(const ::Piotr_Dabrowski::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::Piotr_Dabrowski::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::Piotr_Dabrowski::AddTwoInts > 
template<>
struct MD5Sum< ::Piotr_Dabrowski::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::Piotr_Dabrowski::AddTwoInts >::value();
  }
  static const char* value(const ::Piotr_Dabrowski::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::Piotr_Dabrowski::AddTwoIntsResponse> should match 
// service_traits::DataType< ::Piotr_Dabrowski::AddTwoInts > 
template<>
struct DataType< ::Piotr_Dabrowski::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::Piotr_Dabrowski::AddTwoInts >::value();
  }
  static const char* value(const ::Piotr_Dabrowski::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PIOTR_DABROWSKI_MESSAGE_ADDTWOINTS_H
